### ISSUE TITLE
Single delete function does not work

### ISSUE THREAD

**Issue by Lazarus132** [datlechin/botble-email-log#5]
Please update your plugin. In the current version, the delete function only works via the bulk delete function.

**Comment by Lazarus132** [comment]
The error message always appears:
The DELETE method is not supported for route admin/email-logs. Supported methods: GET, HEAD, POST.

**Comment by Lazarus132** [comment]
For example, to support Youtubers and they support me.

**Comment by datlechin** [comment]
Thanks for report, I will check ASAP
